spring.application.name=api-gateway

server.port=8080


# ============================================================
# Eureka
# ============================================================

eureka.client.service-url.defaultZone=http://localhost:8791/eureka


# ============================================================
# Product Service
# ============================================================

# Gateway endpoint:
# /gateway/products/**

spring.cloud.gateway.server.webflux.routes[0].id=product-service

spring.cloud.gateway.server.webflux.routes[0].uri=lb://product-service

spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/products/gateway/**

# ============================================================
# Order Service
# ============================================================

# Gateway endpoint:
# /gateway/orders/**

spring.cloud.gateway.server.webflux.routes[1].id=order-service

spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service

spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/orders/gateway/**
