spring.application.name=order-service
server.port= 8083
product.service.base-url=http://product-service

# Path of eureka server
eureka.client.service-url.defaultZone = http://localhost:8791/eureka

# Rate Limiter configuration
resilience4j.ratelimiter.instances.productRateLimiter.limit-for-period= 2
resilience4j.ratelimiter.instances.productRateLimiter.limit-refresh-period = 10s
resilience4j.ratelimiter.instances.productRateLimiter.timeout-duration = 1s

#Bulkhead Approach configuration
resilience4j.bulkhead.instances.productService.max-concurrent-calls=2
resilience4j.bulkhead.instances.productService.max-wait-duration=0

#Comment out for Fixed Delay Retry
## Retry: Fixed Delay Interval
## By default retry uses Fixed Delay Interval
#resilience4j.retry.instances.productService.max-attempts=3
#resilience4j.retry.instances.productService.wait-duration=2s

##Comment out for Exponential Backoff Retry
## Retry: Exponential Backoff -> We have to change the configurations only
#resilience4j.retry.instances.productService.max-attempts=4
#resilience4j.retry.instances.productService.wait-duration=1s
#resilience4j.retry.instances.productService.enable-exponential-backoff=true
#resilience4j.retry.instances.productService.exponential-backoff-multiplier=2


# Retry: Exponential Backoff + jitter -> We have to change the configurations only
resilience4j.retry.instances.productService.max-attempts=4
resilience4j.retry.instances.productService.wait-duration=1s
resilience4j.retry.instances.productService.enable-exponential-backoff=true
resilience4j.retry.instances.productService.exponential-backoff-multiplier=2
resilience4j.retry.instances.productService.enable-randomized-wait=true


